# -------------------------------------
# Makefile; AL2016 (v1.00)             
# (c)2016 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex1-1 ex1-2 ex1-3 ex1-4 ex1-5 ex1-6 ex1-7 q1-1 q1-2 q1-3 

ex1-1: ex1-1.c
	$(CC) $(CFLAGS) $(LIBS) ex1-1.c -o ex1-1

ex1-2: ex1-2.c
	$(CC) $(CFLAGS) $(LIBS) ex1-2.c -o ex1-2

ex1-3: ex1-3.c
	$(CC) $(CFLAGS) $(LIBS) ex1-3.c -o ex1-3

ex1-4: ex1-4.c
	$(CC) $(CFLAGS) $(LIBS) ex1-4.c -o ex1-4

ex1-5: ex1-5.c
	$(CC) $(CFLAGS) $(LIBS) ex1-5.c -o ex1-5

ex1-6: ex1-6.c
	$(CC) $(CFLAGS) $(LIBS) ex1-6.c -o ex1-6

ex1-7: ex1-7.c
	$(CC) $(CFLAGS) $(LIBS) ex1-7.c -o ex1-7

q1-1: q1-1.c
	$(CC) $(CFLAGS) $(LIBS) q1-1.c -o q1-1

q1-2: q1-2.c
	$(CC) $(CFLAGS) $(LIBS) q1-2.c -o q1-2

q1-3: q1-3.c
	$(CC) $(CFLAGS) $(LIBS) q1-3.c -o q1-3

clean:
	rm -rf *~  ex1-1 ex1-2 ex1-3 ex1-4 ex1-5 ex1-6 ex1-7 q1-1 q1-2 q1-3 

