# -------------------------------------
# Makefile; AL2016 (v1.00)             
# (c)2016 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex3-1 ex3-10 ex3-11 ex3-2 ex3-3 ex3-4 ex3-5 ex3-6 ex3-7 ex3-8 ex3-9 q3-1 q3-2 q3-3 q3-4 q3-5 

ex3-1: ex3-1.c
	$(CC) $(CFLAGS) $(LIBS) ex3-1.c -o ex3-1

ex3-10: ex3-10.c
	$(CC) $(CFLAGS) $(LIBS) ex3-10.c -o ex3-10

ex3-11: ex3-11.c
	$(CC) $(CFLAGS) $(LIBS) ex3-11.c -o ex3-11

ex3-2: ex3-2.c
	$(CC) $(CFLAGS) $(LIBS) ex3-2.c -o ex3-2

ex3-3: ex3-3.c
	$(CC) $(CFLAGS) $(LIBS) ex3-3.c -o ex3-3

ex3-4: ex3-4.c
	$(CC) $(CFLAGS) $(LIBS) ex3-4.c -o ex3-4

ex3-5: ex3-5.c
	$(CC) $(CFLAGS) $(LIBS) ex3-5.c -o ex3-5

ex3-6: ex3-6.c
	$(CC) $(CFLAGS) $(LIBS) ex3-6.c -o ex3-6

ex3-7: ex3-7.c
	$(CC) $(CFLAGS) $(LIBS) ex3-7.c -o ex3-7

ex3-8: ex3-8.c
	$(CC) $(CFLAGS) $(LIBS) ex3-8.c -o ex3-8

ex3-9: ex3-9.c
	$(CC) $(CFLAGS) $(LIBS) ex3-9.c -o ex3-9

q3-1: q3-1.c
	$(CC) $(CFLAGS) $(LIBS) q3-1.c -o q3-1

q3-2: q3-2.c
	$(CC) $(CFLAGS) $(LIBS) q3-2.c -o q3-2

q3-3: q3-3.c
	$(CC) $(CFLAGS) $(LIBS) q3-3.c -o q3-3

q3-4: q3-4.c
	$(CC) $(CFLAGS) $(LIBS) q3-4.c -o q3-4

q3-5: q3-5.c
	$(CC) $(CFLAGS) $(LIBS) q3-5.c -o q3-5

clean:
	rm -rf *~  ex3-1 ex3-10 ex3-11 ex3-2 ex3-3 ex3-4 ex3-5 ex3-6 ex3-7 ex3-8 ex3-9 q3-1 q3-2 q3-3 q3-4 q3-5 

