# -------------------------------------
# Makefile; AL2016 (v1.01)             
# (c)2016 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -Wno-unused-result -O2
# CFLAGS = -Wall -O2
LIBS = -lm

all: ex6-1 ex6-10 ex6-2 ex6-3 ex6-4 ex6-5 ex6-6 ex6-7 ex6-8 ex6-9 q6-1 q6-2 q6-3 q6-4 q6-5 q6-6 

ex6-1: ex6-1.c
	$(CC) $(CFLAGS) ex6-1.c $(LIBS) -o ex6-1

ex6-10: ex6-10.c
	$(CC) $(CFLAGS) ex6-10.c $(LIBS) -o ex6-10

ex6-2: ex6-2.c
	$(CC) $(CFLAGS) ex6-2.c $(LIBS) -o ex6-2

ex6-3: ex6-3.c
	$(CC) $(CFLAGS) ex6-3.c $(LIBS) -o ex6-3

ex6-4: ex6-4.c
	$(CC) $(CFLAGS) ex6-4.c $(LIBS) -o ex6-4

ex6-5: ex6-5.c
	$(CC) $(CFLAGS) ex6-5.c $(LIBS) -o ex6-5

ex6-6: ex6-6.c
	$(CC) $(CFLAGS) ex6-6.c $(LIBS) -o ex6-6

ex6-7: ex6-7.c
	$(CC) $(CFLAGS) ex6-7.c $(LIBS) -o ex6-7

ex6-8: ex6-8.c
	$(CC) $(CFLAGS) ex6-8.c $(LIBS) -o ex6-8

ex6-9: ex6-9.c
	$(CC) $(CFLAGS) ex6-9.c $(LIBS) -o ex6-9

q6-1: q6-1.c
	$(CC) $(CFLAGS) q6-1.c $(LIBS) -o q6-1

q6-2: q6-2.c
	$(CC) $(CFLAGS) q6-2.c $(LIBS) -o q6-2

q6-3: q6-3.c
	$(CC) $(CFLAGS) q6-3.c $(LIBS) -o q6-3

q6-4: q6-4.c
	$(CC) $(CFLAGS) q6-4.c $(LIBS) -o q6-4

q6-5: q6-5.c
	$(CC) $(CFLAGS) q6-5.c $(LIBS) -o q6-5

q6-6: q6-6.c
	$(CC) $(CFLAGS) q6-6.c $(LIBS) -o q6-6

clean:
	rm -rf *~  ex6-1 ex6-10 ex6-2 ex6-3 ex6-4 ex6-5 ex6-6 ex6-7 ex6-8 ex6-9 q6-1 q6-2 q6-3 q6-4 q6-5 q6-6 

