# -------------------------------------
# Makefile; AL2016 (v1.00)             
# (c)2016 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: q15-1 q15-2 

q15-1: q15-1.c
	$(CC) $(CFLAGS) $(LIBS) q15-1.c -o q15-1

q15-2: q15-2.c
	$(CC) $(CFLAGS) $(LIBS) q15-2.c -o q15-2

clean:
	rm -rf *~  q15-1 q15-2 

