# -------------------------------------
# Makefile; AL2016 (v1.00)             
# (c)2016 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex5-1 ex5-2 ex5-3 ex5-4 ex5-5 ex5-6 ex5-7 q5-1 q5-2 q5-3 q5-4 q5-5 

ex5-1: ex5-1.c
	$(CC) $(CFLAGS) $(LIBS) ex5-1.c -o ex5-1

ex5-2: ex5-2.c
	$(CC) $(CFLAGS) $(LIBS) ex5-2.c -o ex5-2

ex5-3: ex5-3.c
	$(CC) $(CFLAGS) $(LIBS) ex5-3.c -o ex5-3

ex5-4: ex5-4.c
	$(CC) $(CFLAGS) $(LIBS) ex5-4.c -o ex5-4

ex5-5: ex5-5.c
	$(CC) $(CFLAGS) $(LIBS) ex5-5.c -o ex5-5

ex5-6: ex5-6.c
	$(CC) $(CFLAGS) $(LIBS) ex5-6.c -o ex5-6

ex5-7: ex5-7.c
	$(CC) $(CFLAGS) $(LIBS) ex5-7.c -o ex5-7

q5-1: q5-1.c
	$(CC) $(CFLAGS) $(LIBS) q5-1.c -o q5-1

q5-2: q5-2.c
	$(CC) $(CFLAGS) $(LIBS) q5-2.c -o q5-2

q5-3: q5-3.c
	$(CC) $(CFLAGS) $(LIBS) q5-3.c -o q5-3

q5-4: q5-4.c
	$(CC) $(CFLAGS) $(LIBS) q5-4.c -o q5-4

q5-5: q5-5.c
	$(CC) $(CFLAGS) $(LIBS) q5-5.c -o q5-5

clean:
	rm -rf *~  ex5-1 ex5-2 ex5-3 ex5-4 ex5-5 ex5-6 ex5-7 q5-1 q5-2 q5-3 q5-4 q5-5 

